# OpenAPI Petstore
#
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://openapi-generator.tech


#' ApiClient Class
#'
#' Generic API client for OpenAPI client library builds.
#' OpenAPI generic API client. This client handles the client-
#' server communication, and is invariant across implementations. Specifics of
#' the methods and models for each application are generated from the OpenAPI Generator
#' templates.
#'
#' NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
#' Ref: https://openapi-generator.tech
#' Do not edit the class manually.
#'
#' @importFrom httr content_type
#' @export
ApiClient  <- R6::R6Class(
  'ApiClient',
  public = list(
    # base path of all requests
    basePath = "http://petstore.swagger.io/v2",
    # user agent in the HTTP request
    userAgent = "OpenAPI-Generator/0.0.1/r",
    # default headers in the HTTP request
    defaultHeaders = NULL,
    # username (HTTP basic authentication)
    username = NULL,
    # password (HTTP basic authentication)
    password = NULL,
    # API keys
    apiKeys = list(),
    # Access token
    accessToken = NULL,
    # constructor
    initialize = function(basePath=NULL, defaultHeaders=NULL, username=NULL, password=NULL, apiKeys=NULL, accessToken=NULL){
      if (!missing(basePath)) {
        self$basePath <- basePath
      }

      if (!missing(defaultHeaders)) {
        self$defaultHeaders <- defaultHeaders
      }

      if (!missing(username)) {
        self$username <- username
      }

      if (!missing(password)) {
        self$password <- password
      }

      if (!missing(accessToken)) {
        self$accessToken <- accessToken
      }

      if (!missing(apiKeys)) {
        self$apiKeys <- apiKeys
      }

      if (!missing(userAgent)) {
        self$`userAgent` <- 'OpenAPI-Generator/0.0.1/r'
      }
    },
    callApi = function(url, method, queryParams, headerParams, body, ...){
      headers <- httr::add_headers(c(headerParams, self$defaultHeaders))

      if (method == "GET") {
        httr::GET(url, queryParams, headers, ...)
      } else if (method == "POST") {
        httr::POST(url, queryParams, headers, body = body, httr::content_type("application/json"), ...)
      } else if (method == "PUT") {
        httr::PUT(url, queryParams, headers, body = body, httr::content_type("application/json"), ...)
      } else if (method == "PATCH") {
        httr::PATCH(url, queryParams, headers, body = body, httr::content_type("application/json"), ...)
      } else if (method == "HEAD") {
        httr::HEAD(url, queryParams, headers, ...)
      } else if (method == "DELETE") {
        httr::DELETE(url, queryParams, headers, ...)
      } else {
        stop("http method must be `GET`, `HEAD`, `OPTIONS`, `POST`, `PATCH`, `PUT` or `DELETE`.")
      }
    }
  )
)
